In [1]:
from tensorflow.keras.models import load_model
import numpy as np
from werkzeug import secure_filename
from tensorflow.keras.applications import MobileNet
from PIL import Image, ImageFile
from io import BytesIO
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.mobilenet import preprocess_input
from tensorflow.keras.applications.mobilenet import decode_predictions
from flask import Flask, request, jsonify, url_for, render_template, abort, flash,redirect
from werkzeug.wrappers import Request, Response
import uuid
import os
print("np")


np


C:\Users\Sibel\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: The import 'werkzeug.secure_filename' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.utils import secure_filename' instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [2]:
ALLOWED_FILE =set(['jpg','jpeg','png'])
UPLOAD_FOLDER = 'static/uploads'
IMAGE_HEIGHT =32
IMAGE_WIDTH = 32
IMAGE_CHANNELS = 3

print("np")

np


In [3]:
def allowed_file(filename):
    return '.' in filename and \
     filename.rsplit('.',1)[1] in ALLOWED_FILE
print("np")


np


In [4]:
model=load_model('C:/Users/Sibel/Desktop/bitirme_projesi/model/model.h5')
model.summary()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_55 (Conv2D)           (None, 32, 32, 32)        896       
_________________________________________________________________
dropout_55 (Dropout)         (None, 32, 32, 32)        0         
_________________________________________________________________
conv2d_56 (Conv2D)           (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d_28 (MaxPooling (None, 16, 16, 32)        0         
_________________________________________________________________
conv2d_57 (Conv2D)           (None, 16, 16, 64)        18496     
_________________________________________________________________
dropout_56 (Dropout)         (None, 16, 16, 64)        0         
______________________________________

In [ ]:
app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/upload', methods = ['GET', 'POST'])

def upload_image():     
        
  
    file = request.files['image']
    
    if file.filename =='':
        return render_template('index.html', prediction = 'Resim seçmediniz')
    
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        
        print("***"+filename)
       
        ImageFile.LOAD_TRUNCATED_IMAGES = False
        img = Image.open(BytesIO(file.read()))
        img.load()
        img  = img.resize((IMAGE_WIDTH, IMAGE_HEIGHT), Image.ANTIALIAS)
        img.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        
        #Tahmin ettirme
        test_image =image.img_to_array(img) 
        test_image =np.expand_dims(test_image, axis =0) 
        result = model.predict(test_image) 
        
        print(result) 
        if result[0][0]==1: 
            pred='Uçak' 
        elif result[0][1]==1: 
            pred='Otomobil' 
        elif result[0][2]==1: 
            pred='Kuş' 
        elif result[0][3]==1: 
            pred='Kedi'
        elif result[0][4]==1: 
            pred='Geyik'
        elif result[0][5]==1: 
            pred='Köpek'
        elif result[0][6]==1: 
            pred='Kurbağa'
        elif result[0][7]==1: 
            pred='At'
        elif result[0][8]==1: 
            pred='Gemi'
        elif result[0][9]==1: 
            pred='Kamyon' 
        else: 
            pred='Cifar-10 veriseti böyle bir nesneyi içermiyor. '
        
        response = pred
        return render_template('index.html', prediction = 'Tahmin: {}'.format(response))
        
    
    else:
        return render_template('index.html', prediction = 'Geçersiz dosya uzantısı!!')



if __name__=="__main__":
    from werkzeug.serving import run_simple
    run_simple('localhost', 7777, app)


 * Running on http://localhost:7777/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Jul/2020 11:45:26] "GET / HTTP/1.1" 200 -


***at.jpg


127.0.0.1 - - [08/Jul/2020 11:45:38] "POST /upload HTTP/1.1" 200 -


[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


127.0.0.1 - - [08/Jul/2020 11:45:44] "POST /upload HTTP/1.1" 200 -


***gemi.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


127.0.0.1 - - [08/Jul/2020 11:45:48] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [08/Jul/2020 11:46:00] "POST /upload HTTP/1.1" 200 -
127.0.0.1 - - [08/Jul/2020 11:47:12] "POST /upload HTTP/1.1" 200 -


***5c02ed550f25442260cff6ab.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


127.0.0.1 - - [08/Jul/2020 11:48:11] "POST /upload HTTP/1.1" 200 -


***kedii.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


127.0.0.1 - - [08/Jul/2020 11:48:19] "POST /upload HTTP/1.1" 200 -


***download.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
